[tasks.backend]
command = "cargo"
args = ["run", "--bin", "stg_rd"]

[tasks.frontend]
command = "cargo"
args = ["run", "--bin", "stg_rd-frontend"]

[tasks.dev]
dependencies = ["backend", "frontend"] 